"""Initial migration from ORM models

Revision ID: 8f3aac27db9a
Revises:
Create Date: 2025-09-13 09:32:29.847428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3aac27db9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('setting_value', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_table('guild_treasury',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_sand', sa.Integer(), nullable=False),
    sa.Column('total_melange', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expeditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initiator_id', sa.String(), nullable=False),
    sa.Column('initiator_username', sa.String(), nullable=False),
    sa.Column('total_sand', sa.Integer(), nullable=False),
    sa.Column('sand_per_melange', sa.Integer(), nullable=True),
    sa.Column('guild_cut_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melange_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('melange_amount', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.String(), nullable=True),
    sa.Column('admin_username', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('sand_amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedition_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('sand_amount', sa.Integer(), nullable=False),
    sa.Column('melange_amount', sa.Integer(), nullable=False),
    sa.Column('is_harvester', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('sand_amount', sa.Integer(), nullable=False),
    sa.Column('melange_amount', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=True),
    sa.Column('admin_user_id', sa.String(), nullable=False),
    sa.Column('admin_username', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.String(), nullable=True),
    sa.Column('target_username', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('paid_melange', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'total_melange',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'last_updated',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'total_sand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_sand', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'last_updated',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'total_melange',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'paid_melange')
    op.drop_column('users', 'id')
    op.drop_table('guild_transactions')
    op.drop_table('expedition_participants')
    op.drop_table('deposits')
    op.drop_table('melange_payments')
    op.drop_table('expeditions')
    op.drop_table('guild_treasury')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
