"""Initial migration - complete schema with indices and constraints

Revision ID: a6fe5e68863a
Revises: 
Create Date: 2025-09-13 10:37:55.444043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fe5e68863a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_index('ix_global_settings_setting_key', 'global_settings', ['setting_key'], unique=False)
    op.create_table('guild_treasury',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_sand', sa.Integer(), nullable=False),
    sa.Column('total_melange', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guild_treasury_id_desc', 'guild_treasury', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('total_melange', sa.Integer(), nullable=False),
    sa.Column('paid_melange', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_users_leaderboard', 'users', ['total_melange', 'username'], unique=False)
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.create_table('expeditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initiator_id', sa.String(length=50), nullable=False),
    sa.Column('initiator_username', sa.String(length=100), nullable=False),
    sa.Column('total_sand', sa.Integer(), nullable=False),
    sa.Column('sand_per_melange', sa.Integer(), nullable=True),
    sa.Column('guild_cut_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melange_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('melange_amount', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.String(length=50), nullable=True),
    sa.Column('admin_username', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_melange_payments_admin', 'melange_payments', ['admin_user_id'], unique=False)
    op.create_index('ix_melange_payments_user_id', 'melange_payments', ['user_id'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('sand_amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deposits_expedition_id', 'deposits', ['expedition_id'], unique=False)
    op.create_index('ix_deposits_user_created', 'deposits', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_deposits_user_id', 'deposits', ['user_id'], unique=False)
    op.create_table('expedition_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('sand_amount', sa.Integer(), nullable=False),
    sa.Column('melange_amount', sa.Integer(), nullable=False),
    sa.Column('is_harvester', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expedition_participants_expedition_id', 'expedition_participants', ['expedition_id'], unique=False)
    op.create_index('ix_expedition_participants_user_id', 'expedition_participants', ['user_id'], unique=False)
    op.create_table('guild_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('sand_amount', sa.Integer(), nullable=False),
    sa.Column('melange_amount', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=True),
    sa.Column('admin_user_id', sa.String(length=50), nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('target_user_id', sa.String(length=50), nullable=True),
    sa.Column('target_username', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guild_transactions_admin', 'guild_transactions', ['admin_user_id'], unique=False)
    op.create_index('ix_guild_transactions_expedition_id', 'guild_transactions', ['expedition_id'], unique=False)
    op.create_index('ix_guild_transactions_target_user', 'guild_transactions', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_guild_transactions_target_user', table_name='guild_transactions')
    op.drop_index('ix_guild_transactions_expedition_id', table_name='guild_transactions')
    op.drop_index('ix_guild_transactions_admin', table_name='guild_transactions')
    op.drop_table('guild_transactions')
    op.drop_index('ix_expedition_participants_user_id', table_name='expedition_participants')
    op.drop_index('ix_expedition_participants_expedition_id', table_name='expedition_participants')
    op.drop_table('expedition_participants')
    op.drop_index('ix_deposits_user_id', table_name='deposits')
    op.drop_index('ix_deposits_user_created', table_name='deposits')
    op.drop_index('ix_deposits_expedition_id', table_name='deposits')
    op.drop_table('deposits')
    op.drop_index('ix_melange_payments_user_id', table_name='melange_payments')
    op.drop_index('ix_melange_payments_admin', table_name='melange_payments')
    op.drop_table('melange_payments')
    op.drop_table('expeditions')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_index('ix_users_leaderboard', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_guild_treasury_id_desc', table_name='guild_treasury')
    op.drop_table('guild_treasury')
    op.drop_index('ix_global_settings_setting_key', table_name='global_settings')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
